/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EquiposVehiculos;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Axelshade
 */
public class MisEquiposVehiculos extends javax.swing.JInternalFrame {

    DefaultTableModel  modeloTablae;
    DefaultTableModel modeloe;
    DefaultTableModel  modeloTablav;
    DefaultTableModel modelov;
    
    public MisEquiposVehiculos() {
        initComponents();
        CargarTablaMisEquipos();
        CargarTablaMisVehiculos();
    }
    
    public void CargarTablaMisEquipos(){        
        String[] titulos = {"Código","Tipo","Marca","Modelo","Serial","Descripcion"};
        Object[][] data={
                            {"01","Portatil","Asus","x555d","12345678","risueño"}
                        };
        modeloe= new DefaultTableModel(data, titulos);
        tblListaEquipos.setModel(modeloe);         
    }
    
    public void CargarTablaMisVehiculos(){        
        String[] titulos = {"Código","Tipo","Marca","Modelo","Placa","Descripcion"};
        Object[][] data={
                            {"01","Moto","Honda","2011","AAA123","jajaj"}
                        };
        modelov= new DefaultTableModel(data, titulos);
        tblListaVehiculos.setModel(modelov);         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Opciones = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaEquipos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListaVehiculos = new javax.swing.JTable();

        Opciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionesMouseClicked(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        Opciones.add(Modificar);

        Eliminar.setText("Eliminar");
        Eliminar.setComponentPopupMenu(Opciones);
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        Opciones.add(Eliminar);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mis Equipos y Vehiculos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 2, 2), 2, true), "Mis Equipos"));

        tblListaEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblListaEquipos.setComponentPopupMenu(Opciones);
        tblListaEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaEquiposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListaEquipos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 2, 2), 2, true), "Mis Vehiculos"));

        tblListaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblListaVehiculos.setComponentPopupMenu(Opciones);
        tblListaVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaVehiculosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblListaVehiculos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        int posicion,dato1;
        String  dato2;
        posicion=tblListaEquipos.getSelectedRow();
        posicion=tblListaVehiculos.getSelectedRow();
    
        if(posicion>=0){
            dato1=Integer.parseInt(JOptionPane.showInputDialog("Campo a modificar: Tipo (1), "
                    + "Marca(2), Modelo(3), Serial/Placa(4),  Descripcion(5)"));
            dato2=JOptionPane.showInputDialog("Digite el dato a modificar");          
            modeloe.setValueAt(dato2, posicion, dato1);            
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int posicion;        
        posicion=tblListaEquipos.getSelectedRow();    
        if(posicion>=0){
           modeloe.removeRow(posicion);
        }
        
        posicion=tblListaVehiculos.getSelectedRow();    
        if(posicion>=0){
           modelov.removeRow(posicion);
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void OpcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpcionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcionesMouseClicked

    private void tblListaEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaEquiposMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblListaEquiposMouseClicked

    private void tblListaVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaVehiculosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblListaVehiculosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JPopupMenu Opciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblListaEquipos;
    private javax.swing.JTable tblListaVehiculos;
    // End of variables declaration//GEN-END:variables
}
