/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RegistroPersona;

import ConnectBD.Pconnection;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author FGALLARDO
 */
public class Cambiarpass extends javax.swing.JInternalFrame {
    String pas;
     
    
    public Cambiarpass() {
        initComponents();
        
    }
    private int prueba, cedula, id;
    private String contra, pass, pass1, passold;
       
      
    private void contrasena(){
        char claveold[]=jPactual.getPassword();
        char claven[]=jPnueva.getPassword();
        char clavec[]=jPcNueva.getPassword();
        
        String claveol = new String(claveold);
        passold = claveol;
        String clavenew = new String(claven);
        pass1 = clavenew;
        String clavedef = new String(clavec);
        cedula = Integer.parseInt(txtid.getText());
        pass = clavedef;
    }
    
    private void conecMySQL(){
        Pconnection cambio = new Pconnection();
        
        cambio.setSelectInt(("SELECT PERnumDoc FROM persona WHERE PERnumDoc='"+cedula+"'"), "PERnumDoc");
        prueba=cambio.getSelectInt();
        
        cambio.setSelectStr(("SELECT ACCcon FROM acceso as a "
                        + "JOIN persona as p on a.ACCidPerFK=p.PERidPerPK WHERE PERnumDoc = '"+cedula+"'"),
                "ACCcon");
        contra = cambio.getSelectStr();
        
        cambio.setSelectInt(("SELECT PERidPerPK FROM persona Where PERnumDoc = '"+cedula+"'"), "PERidPerPK");
        id = cambio.getSelectInt();
        
        cambio.setSelectMd5(passold, passold);
        passold = cambio.getMd5();
        
        cambio.setSelectMd5(pass1, pass1);
        pass1 = cambio.getMd5();
        
        cambio.setSelectMd5(pass, pass);
        pass = cambio.getMd5();
        
           
        if(cedula==login.loginf.cc){
            
        
            if(cedula==prueba){
             
                if(passold.equals(contra)){
                
                    if(pass1.equals(pass)){
                    
                        cambio.setUpdate("UPDATE acceso SET ACCcon = '"+pass+"'"+" WHERE ACCidPerFK = "+id);
            
                        JOptionPane.showMessageDialog(null, "Su contraseña Fue cambiada Con Exito");
                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(null, "Las contraseñas no son iguales",
                        "Error de contraseña",JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Su contraseña no Fue cambiada",
                        "Error de contraseña anterior",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Usuario no Valido",
                    "Error de Usuario",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Usuario no Coincide con el usuario Logueado",
                    "Error de Usuario",JOptionPane.ERROR_MESSAGE);
        }
        cambio.cerrarConexion();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPactual = new javax.swing.JPasswordField();
        jPnueva = new javax.swing.JPasswordField();
        jPcNueva = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cambio de Contraseña");

        jLabel1.setText("Digite su contraseña actual:");

        jPcNueva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPcNuevaKeyPressed(evt);
            }
        });

        jLabel2.setText("Comfirme su nueva contraseña:");

        jLabel3.setText("Digite su nueva contraseña:");

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidKeyTyped(evt);
            }
        });

        jLabel4.setText("Ingrese el usuario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtid, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jPactual, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jPnueva, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPcNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jButton1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPactual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPcNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txtid.getText().equals(null)){
            JOptionPane.showMessageDialog(null, "El campo Usuario no puede estar vacío");
        }else{
            contrasena();
            conecMySQL();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyTyped
        char car = evt.getKeyChar();
        if (Character.isLetter(car)){
            evt.consume();
            getToolkit().beep();
        }
        if (Character.isSpaceChar(car)){
            evt.consume();
        }
    }//GEN-LAST:event_txtidKeyTyped

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            contrasena();
            conecMySQL();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jPcNuevaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPcNuevaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            contrasena();
            conecMySQL();
        }
    }//GEN-LAST:event_jPcNuevaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPactual;
    private javax.swing.JPasswordField jPcNueva;
    private javax.swing.JPasswordField jPnueva;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
