/*Q                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             q
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RegistroPersona;
import ConnectBD.Pconnection;
import EquiposVehiculos.SelEquipoVehiculo;
import RegistroPersona.Maven.jFrameCamera;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import prototipo.Principal;
import static prototipo.Principal.Escritorio;
/**
 *
 * @author SENA
 */
public class RegistroPersona extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form RegistroPersona
     */
    
    // inicio de conexion a la base de datos
    Pconnection cargar = new Pconnection();
    
    private int docu;
    File ruta = new File(System.getenv("APPDATA")+"/SCESS/Images");
    
    
    
    public RegistroPersona() {
        initComponents();
        
       
        cargar.getConexion();
            
      /*  cargar.setLlenaCombo("Select FICnumFic from ficha", "FICnumFic");
        cbxFicha.addItem(cargar.getLlenaCombo());
                
        cargar.setLlenaCombo("Select CENnomCen from centros ", "CENnomCen");
        cbxCentro.addItem(cargar.getLlenaCombo());
        */
    }
    
    public static void actfoto(String rt){
        ImageIcon foto = new ImageIcon(rt);
        ImageIcon ico = new ImageIcon(foto.getImage().getScaledInstance(jLFoto.getWidth(), jLFoto.getHeight(), Image.SCALE_DEFAULT));
        jLFoto.setIcon(ico);
        
        
        
        
        //File ruta = new File(System.getenv("APPDATA")+"/SCESS/Images");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre1 = new javax.swing.JTextField();
        txtNombre2 = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        cbxFicha = new javax.swing.JComboBox<>();
        cbxTipoDoc = new javax.swing.JComboBox<>();
        txtDocumento = new javax.swing.JTextField();
        cbxGenero = new javax.swing.JComboBox<>();
        cbxRh = new javax.swing.JComboBox<>();
        cbxTipUser = new javax.swing.JComboBox<>();
        cbxCentro = new javax.swing.JComboBox<>();
        cbxUsuario = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        cbxRol = new javax.swing.JComboBox<>();
        txtTelefono = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPimg = new javax.swing.JPanel();
        jLFoto = new javax.swing.JLabel();
        jbtnImg = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Registrar Persona");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Datos Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        cbxFicha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Otra" }));
        cbxFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFichaActionPerformed(evt);
            }
        });

        cbxTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "R.C", "T.I.", "C.C.", "C.E" }));

        txtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDocumentoKeyTyped(evt);
            }
        });

        cbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Femenino", "Masculino" }));

        cbxRh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "A+", "B+", "AB+", "O+", "A-", "B-", "AB-", "O-" }));

        cbxTipUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Instructor", "Aprendiz", "Contratista", "Administrativo" }));

        cbxCentro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Otra" }));
        cbxCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCentroActionPerformed(evt);
            }
        });

        cbxUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Activo", "Inactivo" }));

        cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Administrador", "Operador", "Usuario", "Ninguno" }));

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularKeyTyped(evt);
            }
        });

        jLabel24.setText("E-Mail");

        jLabel17.setText("Tipo Documento:   (*)");

        jLabel21.setText("N° Telefonico:   (*)");

        jLabel16.setText("2do Apellido:");

        jLabel1.setText("Tipo Usuario   (*)");

        jLabel22.setText("N° Celular");

        jLabel15.setText("1er Apellido:   (*)");

        jLabel23.setText("Direccion:");

        jLabel18.setText("Doc. N°:  (*)");

        jLabel14.setText("2do Nombre:");

        jLabel20.setText("Tipo RH   (*)");

        jLabel2.setText("Ficha Formacion  (*)");

        jLabel3.setText("Centro   (*)");

        jLabel13.setText("1er Nombre:  (*)");

        jLabel19.setText("Genero   (*)");

        jPimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPimg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLFoto.setText("FOTO");
        jLFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLFotoMouseClicked(evt);
            }
        });
        jPimg.add(jLFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 150, 170));

        jbtnImg.setText("Agregar Imagen");
        jbtnImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnImgActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar Cambios");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        btnGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGuardarKeyPressed(evt);
            }
        });

        jButton3.setText("Agregar Equipo y/o Vehiculo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Estado Usuario");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel25.setText("Rol Usuario   (*)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel22)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCelular))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel24))
                                    .addGap(18, 18, 18)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel25))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(13, 13, 13)
                                            .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cbxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel16))
                                    .addGap(25, 25, 25)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPimg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtnImg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(cbxCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel20)
                                            .addGap(18, 18, 18)
                                            .addComponent(cbxRh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1)
                                            .addGap(2, 2, 2)
                                            .addComponent(cbxTipUser, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbxTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton3)
                            .addGap(18, 18, 18)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPimg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbxFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnImg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel13)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel14)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(cbxTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(cbxRh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbxTipUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbxCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(jButton3)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        SelEquipoVehiculo obj=new SelEquipoVehiculo();
        Principal.Escritorio.add(obj);
        obj.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cargar.cerrarConexion();
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        docu = 0;
        int id=0;
        cargar.setSelectInt("Select PERnumDoc from persona where PERnumDoc ='"+txtDocumento.getText()+"'","PERnumDoc");
        docu = cargar.getSelectInt();
        
        cargar.setSelectInt("Select PERidPerPK from persona","PERidPerPK");
        id=cargar.getSelectInt();
        
        FileInputStream fi = null;
        
        JOptionPane.showMessageDialog(null, "Id persona actual"+id);
        
        id++;
        
        JOptionPane.showMessageDialog(null, "Id persona nuevo"+id);
        
        JOptionPane.showMessageDialog(null,(cbxCentro.getSelectedIndex()));
        
        if(docu>0){
            JOptionPane.showMessageDialog(null, "El documento "+txtDocumento.getText()+" ya se encuentra registrado");
            
        }else{
            
            if((cbxTipoDoc.getSelectedIndex()==0)||(txtDocumento.getText().equals(""))||
                (txtNombre1.getText().equals(""))||(txtApellido1.getText().equals(""))||
                (cbxGenero.getSelectedIndex()==0)||
                (txtTelefono.getText().equals(""))||(cbxRh.getSelectedIndex()==0)||
                (cbxTipUser.getSelectedIndex()==0)||
                ((cbxCentro.getSelectedIndex()-1)==0)||((cbxFicha.getSelectedIndex()-1)==0)){
            JOptionPane.showMessageDialog(null, "Hay Campos marcados con (*) vacios que son obligatorios");
            }else{
                
            
            if(txtNombre2.getText().equals("")){
                txtNombre2.setText(" ");
            }
            if(txtApellido2.getText().equals("")){
                txtApellido2.setText(" ");
            }
            if(txtDireccion.getText().equals("")){
                txtDireccion.setText(" ");
            }
            if(txtCelular.getText().equals("")){
                txtCelular.setText("0");
            }
            if(txtEmail.getText().equals("")){
                txtEmail.setText(" ");
            }

                
            String insert = "INSERT INTO persona (PERidPerPK, PERidDocFK, PERnumDoc, PERnom1, PERnom2, PERape1, PERape2, PERidGenFK, PERdir, PERtelFij, PERcel, PERcor, PERidRhFK, PERidTiPeFK, PERidRolFK, PERidCenFK, PERidFicFK, PERfoto) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps = null;

            try {

                Pconnection grabar = new Pconnection();
                String r=ruta+"/"+txtDocumento.getText()+".png";
                File file = new File(r);
                fi = new FileInputStream(file);

                ps = grabar.getConexion().prepareStatement(insert);
                ps.setInt(1,id);
                ps.setInt(2,cbxTipoDoc.getSelectedIndex());
                ps.setInt(3,Integer.parseInt(txtDocumento.getText()));
                ps.setString(4,txtNombre1.getText());
                ps.setString(5,txtNombre2.getText());
                ps.setString(6,txtApellido1.getText());
                ps.setString(7,txtApellido2.getText());
                ps.setInt(8,cbxGenero.getSelectedIndex());
                ps.setString(9,txtDireccion.getText());
                ps.setInt(10,(Integer.parseInt(txtTelefono.getText())));
                ps.setInt(11,(Integer.parseInt(txtCelular.getText())));
                ps.setString(12,txtEmail.getText());
                ps.setInt(13,cbxRh.getSelectedIndex());
                ps.setInt(14,cbxTipUser.getSelectedIndex());
                ps.setInt(15,cbxRol.getSelectedIndex());
                ps.setInt(16,(cbxCentro.getSelectedIndex())-1);
                ps.setInt(17,(cbxFicha.getSelectedIndex())-1);
                ps.setBinaryStream(18,fi,(int)file.length());
                ps.executeUpdate(); 
                JOptionPane.showMessageDialog(null,"Registro almacenado con Exito.! ");
            }catch(SQLException e){
                System.out.println(e.getMessage());

            }       catch (FileNotFoundException ex) {
                        Logger.getLogger(RegistroPersona.class.getName()).log(Level.SEVERE, null, ex);
                    }

                
                
                
                
                
                
                /*
                cargar.setInsert("INSERT INTO persona (PERidPerPK, PERidDocFK, "
                + "PERnumDoc, PERnom1, PERnom2, PERape1, PERape2, "
                + "PERidGenFK, PERdir, PERtelFij, PERcel, PERcor, "
                + "PERidRhFK, PERidTiPeFK, PERidRolFK, PERidCenFK, PERidFicFK) VALUES "
                +"("+id+","+cbxTipoDoc.getSelectedIndex()+","+txtDocumento.getText()+",'"+txtNombre1.getText()+"','"
                +txtNombre2.getText()+"','"+txtApellido1.getText()+"','"+txtApellido2.getText()+"',"+cbxGenero.getSelectedIndex()+",'"
                +txtDireccion.getText()+"',"+txtTelefono.getText()+","+txtCelular.getText()+",'"+txtEmail.getText()+"',"+cbxRh.getSelectedIndex()
                +","+cbxTipUser.getSelectedIndex()+","+cbxRol.getSelectedIndex()+","
                + (cbxCentro.getSelectedIndex()-1)+","+(cbxFicha.getSelectedIndex()-1)+")");
                */
                
                cargar.cerrarConexion();
                dispose();
            }
        }
        
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cbxFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFichaActionPerformed
        
        if(cbxFicha.getSelectedItem().equals("Otra")){
            RegistroFicha obj1 = new RegistroFicha();
            Escritorio.add(obj1);
            obj1.show();
        }else{
            
        }
        
        
    }//GEN-LAST:event_cbxFichaActionPerformed

    private void cbxCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCentroActionPerformed
        if(cbxCentro.getSelectedItem().equals("Otra")){
            RegistroCentro obj2 = new RegistroCentro();
            Escritorio.add(obj2);
            obj2.show();
        }else{
            
            if(cbxCentro.getSelectedIndex()>0){
                
            }
            
        }
    }//GEN-LAST:event_cbxCentroActionPerformed

    private void jbtnImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImgActionPerformed
       /* MyIcon icon = new MyIcon();
        String[] option ={"Cargar Imagen", "Fotografia"};
        int sel = JOptionPane.showOptionDialog(null, "Selecciona la opcion correcta", "Cargar Imagen", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, (Icon) icon, option, option[0]);
        
        if(sel==0){
            JFileChooser j = new JFileChooser();
            int ap = j.showOpenDialog(this);
            if(ap==JFileChooser.APPROVE_OPTION){
                ruta = j.getSelectedFile().getAbsolutePath();
                ImageIcon foto = new ImageIcon(ruta);
                Icon icono = new ImageIcon(
                foto.getImage().getScaledInstance(
                jLFoto.getWidth(),jLFoto.getHeight(),Image.SCALE_DEFAULT)
                );
                jLFoto.setIcon(icono);
                this.repaint();
            }
        }else if(sel==1){*/
            jFrameCamera window = new jFrameCamera();
            Escritorio.add(window);
            window.show();
        //}
    }//GEN-LAST:event_jbtnImgActionPerformed

    private void txtDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoKeyTyped
        char car = evt.getKeyChar();
        if (Character.isLetter(car)){
            evt.consume();
            getToolkit().beep();
        }
        if (Character.isSpaceChar(car)){
            evt.consume();
        }
    }//GEN-LAST:event_txtDocumentoKeyTyped

    private void txtCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyTyped
        char car = evt.getKeyChar();
        if (Character.isLetter(car)){
            evt.consume();
            getToolkit().beep();
        }
        if (Character.isSpaceChar(car)){
            evt.consume();
        }
    }//GEN-LAST:event_txtCelularKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char car = evt.getKeyChar();
        if (Character.isLetter(car)){
            evt.consume();
            getToolkit().beep();
        }
        if (Character.isSpaceChar(car)){
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void btnGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuardarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
        }
    }//GEN-LAST:event_btnGuardarKeyPressed

    private void jLFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLFotoMouseClicked
        
        
    }//GEN-LAST:event_jLFotoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    public static javax.swing.JComboBox<String> cbxCentro;
    public static javax.swing.JComboBox<String> cbxFicha;
    public static javax.swing.JComboBox<String> cbxGenero;
    public static javax.swing.JComboBox<String> cbxRh;
    public static javax.swing.JComboBox<String> cbxRol;
    public static javax.swing.JComboBox<String> cbxTipUser;
    public static javax.swing.JComboBox<String> cbxTipoDoc;
    public static javax.swing.JComboBox<String> cbxUsuario;
    private javax.swing.JButton jButton3;
    public static javax.swing.JLabel jLFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPimg;
    private javax.swing.JButton jbtnImg;
    public static javax.swing.JTextField txtApellido1;
    public static javax.swing.JTextField txtApellido2;
    public static javax.swing.JTextField txtCelular;
    public static javax.swing.JTextField txtDireccion;
    public static javax.swing.JTextField txtDocumento;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtNombre1;
    public static javax.swing.JTextField txtNombre2;
    public static javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

        
}
